//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_Cine
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CineEntities : DbContext
    {
        public CineEntities()
            : base("name=CineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Calificaciones> Calificacioness { get; set; }
        public virtual DbSet<Carteleras> Cartelerass { get; set; }
        public virtual DbSet<Generos> Geneross { get; set; }
        public virtual DbSet<Peliculas> Peliculass { get; set; }
        public virtual DbSet<Reservas> Reservass { get; set; }
        public virtual DbSet<Sedes> Sedess { get; set; }
        public virtual DbSet<TiposDocumentos> TiposDocumentoss { get; set; }
        public virtual DbSet<Usuarios> Usuarioss { get; set; }
        public virtual DbSet<Versiones> Versioness { get; set; }
    }
}
